---
# Edits /etc/default/grub in the target before grub-mkconfig runs.
overwrite: false
prefer_grub_d: false
keep_distributor: false
kernel_params:
    - "quiet"
    - "loglevel=3"
defaults:
    GRUB_TIMEOUT: 5
    GRUB_TIMEOUT_STYLE: "menu"
    GRUB_DEFAULT: "0"
    GRUB_DISABLE_SUBMENU: true
    GRUB_DISABLE_RECOVERY: true
always_use_defaults: true
