---
overwrite: false
defaults:
    GRUB_TIMEOUT: 5
    GRUB_TIMEOUT_STYLE: "menu"
    GRUB_DISTRIBUTOR: "SimulationOS"
    GRUB_CMDLINE_LINUX_DEFAULT: "quiet loglevel=3"
    GRUB_CMDLINE_LINUX: ""
    GRUB_ENABLE_CRYPTODISK: false
