---
extraMounts:
    - device: proc
      fs: proc
      mountPoint: /proc
    - device: sys
      fs: sysfs
      mountPoint: /sys
    - device: /dev
      mountPoint: /dev
      options: [ bind ]
    - device: tmpfs
      fs: tmpfs
      mountPoint: /run
    - device: /run/udev
      mountPoint: /run/udev
      options: [ bind ]
    - device: efivarfs
      fs: efivarfs
      mountPoint: /sys/firmware/efi/efivars
      efi: true

mountOptions:
    default: defaults,noatime
    btrfs:   defaults,noatime,compress=zstd
    xfs:     defaults,noatime
    f2fs:    defaults,noatime

btrfsSubvolumes:
    - mountPoint: /
      subvolume:  /@
    - mountPoint: /home
      subvolume:  /@home
    - mountPoint: /var/log
      subvolume:  /@log
    - mountPoint: /var/cache/pacman/pkg
      subvolume:  /@pkg
