# SimulationOS - hyprlock
background {
    monitor =
    path = /usr/share/backgrounds/simulationos/simulationos-alpha.png
    blur_passes = 2
    blur_size = 6
}

input-field {
    monitor =
    size = 320, 46
    outline_thickness = 2
    dots_center = true
    outer_color = rgb(1793d1)
    inner_color = rgb(14161a)
    font_color = rgb(e6e6e6)
    fail_color = rgb(c0392b)
    placeholder_text = <span foreground="##888888">Password</span>
    position = 0, -40
    halign = center
    valign = center
}

label {
    monitor =
    text = SimulationOS
    color = rgba(230, 230, 230, 1.0)
    font_size = 30
    font_family = Fira Sans
    position = 0, 60
    halign = center
    valign = center
}
